### ISSUE TITLE
Clarify pdoc specs for `description` sections

### ISSUE THREAD

**Issue by puzrin** [tobie/pdoc#4]
That's a proposal to update `PDoc` specs, after discussing `NDoc` & updating `Prototype` sources.

https://github.com/nodeca/ndoc/issues/9

Description section should be separated from previous one (EBNF, tags,..) by empty line. In other case it will be impossible to 100% correctly decide, where description starts.

**Comment by tobie** [comment]
Pull request on https://github.com/tobie/pdoc/tree/gh-pages? Not sure that's even possible.

**Comment by puzrin** [comment]
I mean specs on this page: http://pdoc.org/syntax.html .

**Comment by tobie** [comment]
Yeah, that's hosted by github pages and the src code is here:  https://github.com/tobie/pdoc/tree/gh-pages
